server:
  port: 8030


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: web_store
    password: 1021329395
    url: jdbc:mysql://localhost:3306/web_store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #在下面追加如下内容   web_store_manager
    redis:
      host: 127.0.0.1
      port: 6379
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  resources:
    static-locations: clasaspath:static/2


mybatis:
   configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

image:
  config:
    type:
      - jpg
      - jpeg
      - png
    path: static/images/
jwt:
  config:
    key: SecretKey #服务端加密所使用的密文（自拟）
    ttl: 21600000 #毫秒
